sudo: reuired
services:
  - docker
before_install:
  - docker build -t test_me -f Dockerfile.dev .
script:
  - docker run -e CI=true test_me npm run test
deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-training-react
  env: DockerTrainingReact-env
  bucket_name: elasticbeanstalk-eu-west-1-839829880722
  bucket_path: docker-training-react
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
